PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/e6af32c88fb7c011a09ca858939eb503fb7933cb

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (172e435ec01b8484b38e2c70bf30e25530f203ca)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...e6af32c88fb7c011a09ca858939eb503fb7933cb

e6af32c88f (HEAD, origin/master) Run nxstyle against all files modified by PR 848
2f7e003ef8 arch/arm/src/armv7-m:  Use Apache 2.0 license
048d4954a0 crypto: nxstyle fixes
e6b47ea948 video: videomode: nxstyle cleanup
7ddf7c6c25 binfmt: nxstyle fixes
02ab0cd149 stm32: Fix typos, wrong comments, and nxstyle.
31332904dd Added support to crashdump for rx65n on sbram
40eb87d8b4 boards: maix-bit: Update instructions for kostest
ad9db974cb mm: Fix heap corruption in protected build
79589eca1a cxd56: replace Sony return values

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/51cbd422271891ae287111b180e33275b109278d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (172e435ec01b8484b38e2c70bf30e25530f203ca)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...51cbd422271891ae287111b180e33275b109278d

51cbd422 (HEAD -> master, origin/master) Revert "build.yml: Remove -G from cibuild.sh command line"
2749e646 system: nxplayer & nxrecorder: nxstyle fixes
1697c649 examples: nxwidget: nxstyle fixes
c9eaf0be examples: i2sloop: nxstyle fixes
3cdb8107 examples: i2schar: nxstyle fixes
989988fa build.yml: Remove -G from cibuild.sh command line
f18b283e nshlib: add printf command to README.TXT
63288eb8 fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope
68ed2a2a build.yaml: Change arm-11 to arm-12
0c84e22a example: Remove all APPNAME from Makefile